pipeline {
   agent any
   parameters {
       string(name:'Git_Branch',defaultValue:'master',description:'enter git repo')
       string(nmae:'Git_Tag',defaultValue:'',description:'')
   }
   tools{
       gradle 'Gradle_6.6.1'
   }

   stages {
   	  stage('init') {
   	  	steps{
   	  		script {
   	  			sh 'mkdir -p ${WORKSPACE}/project'
   	  		}
   	  	}
   	  }
   
   
      stage('SCM') {
         steps { dir("${WORKSPACE}/project"){
         		script {
         			def repoUrl='https://github.com/dongzhi1129/spring-boot-init-project.git'
		            git branch:params.Git_Branch,url:repoUrl
		            def commitId = sh returnStdout:true,script:'git rev-parse --short HEAD'
		            if(params.Git_Tag != "") {
		                 def G_tag = params.Git_Tag
		                 sh "cd ${WORKSPACE}/project && git checkout ${G_tag}"
		             }
		             def G_version = (params.Git_Tag != ""?params.Git_Tag:"latest")
		             print G_version
         		}
             
             
         }
            
         }
      }
   }
}